version: '3'
services:

  db:
    build:
      context: .
      dockerfile: ./db/postgres/Dockerfile
    container_name: db
    env_file: 
      - ./db/postgres/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /home/johannes/.local/ssl/certs/cwe/server.crt:/etc/ssl/private/server.crt
      - /home/johannes/.local/ssl/certs/cwe/server.key:/etc/ssl/private/server.key
    

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    restart: yes
    depends_on:
      - db
    env_file: ./server/.env
    ports:
      - "443:443"
    volumes:
      - /home/johannes/.local/ssl/certs/cwe:/ssl/certs/cwe
      - /home/johannes/Projects/cwe/server/.env:/usr/src/app/.env

volumes:
  pgdata:
