name: Rust Application CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Ansible
      run: |
        sudo apt update
        sudo apt install ansible
    - name: Run Ansible Playbook
      run: ansible-playbook -i hosts.ini deploy.yml
